In [3]:
import numpy as np

In [4]:
#PROBLEM A (REPRODUCIBLE NORMALIZATION)
np.random.seed(211)
X = np.random.randint(10, 101, size=(5, 5))

In [7]:
x_bar = np.mean(X)
sigma = np.std(X)
X_normalized = (X - x_bar) / sigma

In [8]:
print( "PROBLEM A" )

PROBLEM A


In [10]:
print("Original Array (X):\n", X)

Original Array (X):
 [[16 80 14 52 85]
 [26 86 40 24 57]
 [99 12 29 35 39]
 [25 33 24 29 83]
 [26 52 27 40 77]]


In [12]:
print("\nNormalized Array (X_normalized):\n", X_normalized)


Normalized Array (X_normalized):
 [[-1.11620872  1.39919121 -1.19481496  0.29870374  1.59570683]
 [-0.72317748  1.63500995 -0.17293374 -0.80178373  0.49521936]
 [ 2.14595056 -1.27342121 -0.60526811 -0.36944936 -0.21223687]
 [-0.7624806  -0.44805561 -0.80178373 -0.60526811  1.51710058]
 [-0.72317748  0.29870374 -0.68387435 -0.17293374  1.28128184]]


In [13]:
print("\nMean of Normalized Array:", np.mean(X_normalized))


Mean of Normalized Array: 8.881784197001253e-17


In [14]:
print("Std Dev of Normalized Array:", np.std(X_normalized))

Std Dev of Normalized Array: 1.0


In [15]:
np.save("X_normalized.npy", X_normalized)

In [20]:
#PROBLEM B(CUBES DIVISIBLE BY 4)
C = (np.arange(1, 101) ** 3).reshape(10, 10)
div_by_4 = C[C % 4 == 0]

In [22]:
print("Problem B")

Problem B


In [23]:
print("Shape of C:", C.shape)

Shape of C: (10, 10)


In [25]:
print("Elements Divisible by 4:\n", div_by_4)

Elements Divisible by 4:
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]


In [26]:
print("Number of Selected Elements:", len(div_by_4))

Number of Selected Elements: 50


In [27]:
np.save("div_by_4.npy", div_by_4)

In [29]:
#PROBLEM C(ABOVE-MEAN SQUARES)
S = (np.arange(1, 37) ** 2).reshape(6, 6)
S_mean = np.mean(S)

In [30]:
above_mean = S[S>S_mean]

In [31]:
print("Problem C")

Problem C


In [32]:
print("Array(S):\n", S)

Array(S):
 [[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]


In [33]:
print("Mean of S:", S_mean)

Mean of S: 450.1666666666667


In [34]:
print("Elements Above Mean:\n", above_mean)

Elements Above Mean:
 [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]


In [35]:
print("Number of Selected Elements:", len(above_mean))

Number of Selected Elements: 15


In [36]:
np.save("above_mean.npy", above_mean)

In [ ]:
#END